CREATE TABLE IF NOT EXISTS HASHUSER (
  HASH VARCHAR(6) NOT NULL PRIMARY KEY,
  USER_ID VARCHAR(36),
  URL_ORIGINAL varchar(255),
  CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
  UPDATED_AT TIMESTAMPTZ DEFAULT NOW()
);
